swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /places/:
    get:
      tags:
      - places
      description: get Places
      operationId: PlacesController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Places'
        "403":
          description: ""
    post:
      tags:
      - places
      description: create Places
      operationId: PlacesController.Post
      parameters:
      - in: body
        name: body
        description: body for Places content
        required: true
        schema:
          $ref: '#/definitions/models.Places'
      responses:
        "201":
          description: '{int} models.Places'
        "403":
          description: body is empty
  /places/{id}:
    get:
      tags:
      - places
      description: get Places by id
      operationId: PlacesController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Places'
        "403":
          description: :id is empty
    put:
      tags:
      - places
      description: update the Places
      operationId: PlacesController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Places content
        required: true
        schema:
          $ref: '#/definitions/models.Places'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Places'
        "403":
          description: :id is not int
    delete:
      tags:
      - places
      description: delete the Places
      operationId: PlacesController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  models.Places:
    title: Places
    type: object
    properties:
      Id:
        type: integer
        format: int64
      Name:
        type: string
      Review:
        type: string
tags:
- name: places
  description: |
    PlacesController operations for Places
